--blank-lines-after-declarations
--blank-lines-after-procedures
--blank-lines-before-block-comments
--braces-on-if-line
--braces-on-func-def-line
--braces-on-struct-decl-line
--cuddle-else
       --no-space-after-casts
--case-indentation8
--use-tabs
--tab-size8
--dont-break-procedure-type
--swallow-optional-blank-lines

