post_install() {
		cat <<EOF > speechd-upd.service
[Unit]
Description=speechd-up, a server to connect SpeakUp to speech-dispatcher
After=syslog.target

[Service]
Type=forking
ExecStart=/usr/bin/speechd-upd -d

[Install]
WantedBy=default.target

EOF

  install -Dm644 speechd-upd.service "${pkgdir}/usr/lib/systemd/system/speechd-upd.service"

}

post_upgrade() {
  post_install
}

pre_remove() {

}


